/** Policy setting definition with tooltip content */
export interface PolicySettingDef {
  key: string;
  label: string;
  unit?: string;
  min: number;
  max: number;
  description: string;
  zeroTrust: string;
  communityTrust: string;
  whereUsed: string;
  /** Section for grouping in UI. All peeling-related (history, confidence, thresholds) live together. */
  section?: "trustRange" | "dust" | "peeling";
}

export const POLICY_SETTINGS: PolicySettingDef[] = [
  {
    key: "sovereignCap",
    label: "Sovereign Cap",
    unit: "$",
    min: 0,
    max: 1_000_000,
    description: "Max transaction amount (USD) for auto-approval without MFA. Above this, MFA is required. Also used for peeling: flag targets whose past peel (USD) exceeded this cap. Peel min: Zero Trust 1% of cap, Community Trust 50%.",
    zeroTrust: "$0 — every transaction requires MFA.",
    communityTrust: "$500 — low-value tx to known entities auto-approve.",
    whereUsed: "Trust-Range evaluation (EvaluateTrustRangeAsync)",
    section: "trustRange",
  },
  {
    key: "sovereignCapWindowHours",
    label: "Sovereign Cap Hour Window",
    unit: "hrs",
    min: 0,
    max: 720,
    description: "Hours over which the Sovereign Cap applies. 0 = not applicable (all tx require MFA). 24 = per day. The cap is enforced as a rolling sum of tx amounts within this window.",
    zeroTrust: "0 — all transactions require MFA; no cap window.",
    communityTrust: "24 — daily cap; resets every 24 hours.",
    whereUsed: "Trust-Range evaluation (rolling sum)",
    section: "trustRange",
  },
  {
    key: "maxRiskFloor",
    label: "Allow Threshold (max risk for auto-approve)",
    min: 0,
    max: 100,
    description: "Max risk for low-risk assessment. Risk ≤ this (with cap/confidence) → Low risk.",
    zeroTrust: "0 — no risk tolerated; all tx require MFA.",
    communityTrust: "40 — heuristic-led; moderate risk auto-approves.",
    whereUsed: "Trust-Range evaluation",
    section: "trustRange",
  },
  {
    key: "blockThreshold",
    label: "Block Threshold (min risk for auto-block)",
    min: 0,
    max: 100,
    description: "Min risk for high-risk assessment. Risk ≥ this → High risk. Between Allow and Block = Moderate risk.",
    zeroTrust: "50 — strict; high risk auto-blocked.",
    communityTrust: "80 — heuristic-led; only very high risk blocked.",
    whereUsed: "Trust-Range evaluation",
    section: "trustRange",
  },
  {
    key: "minConfidenceCeiling",
    label: "Confidence Ceiling (min)",
    unit: "%",
    min: 0,
    max: 100,
    description: "Minimum confidence score required for auto-approval. Below this, MFA is required. Used with peeling/history context.",
    zeroTrust: "100% — only fully verified tx pass.",
    communityTrust: "60% — heuristic-led; lower confidence acceptable.",
    whereUsed: "Trust-Range evaluation",
    section: "trustRange",
  },
  {
    key: "dustUsdCeiling",
    label: "Dust USD Ceiling",
    unit: "$",
    min: 0,
    max: 100,
    description: "Max USD per outbound tx considered 'dust'. Txs below this count toward dusting detection.",
    zeroTrust: "$2 — stricter dust detection.",
    communityTrust: "$5 — standard; avoids false positives on micro-payments.",
    whereUsed: "Behavior: Dusting (AnalyzeDispersion)",
    section: "dust",
  },
  {
    key: "matureWalletDustBlockThreshold",
    label: "Mature Wallet Dust Block",
    min: 1,
    max: 20,
    description: "Dust tx count that triggers BLOCK for mature wallets (>1y). Immature wallets block on any dust.",
    zeroTrust: "2 — block sooner.",
    communityTrust: "5 — fewer false positives for high-volume wallets.",
    whereUsed: "Behavior: Dusting",
    section: "dust",
  },
  {
    key: "peelingHeavyRecipients",
    label: "Peeling Heavy Recipients",
    min: 2,
    max: 50,
    description: "Unique recipients in outbound history that trigger 'Heavy Dispersion' BLOCK.",
    zeroTrust: "5 — stricter peeling detection.",
    communityTrust: "10 — standard dispersion threshold.",
    whereUsed: "Behavior: Peeling",
    section: "peeling",
  },
  {
    key: "peelingSuspectedRecipients",
    label: "Peeling Suspected Recipients",
    min: 2,
    max: 20,
    description: "Unique recipients that trigger 'Suspected Dispersion' CAUTION.",
    zeroTrust: "2 — any dispersion is suspicious.",
    communityTrust: "2 — same; low threshold for caution.",
    whereUsed: "Behavior: Peeling",
    section: "peeling",
  },
  {
    key: "fastPeelWindowMinutes",
    label: "Fast Peel Window (min)",
    unit: "min",
    min: 5,
    max: 120,
    description: "Minutes after inbound: large outbound within this window = Fast Heavy Peel (BLOCK). Bot-like timing.",
    zeroTrust: "15 — stricter; any quick drain is suspicious.",
    communityTrust: "30 — standard; catches automated peeling.",
    whereUsed: "Behavior: Peeling (fast peel detection)",
    section: "peeling",
  },
  {
    key: "botLikeWindowMinutes",
    label: "Bot-Like Window (min)",
    unit: "min",
    min: 1,
    max: 10,
    description: "Multiple outbound txs within this many minutes = bot-like timing. Combined with dispersion = BLOCK.",
    zeroTrust: "1 — very strict.",
    communityTrust: "2 — standard.",
    whereUsed: "Behavior: Peeling (bot-like timing)",
    section: "peeling",
  },
  {
    key: "evenDivisionTolerance",
    label: "Even Division Tolerance",
    unit: "%",
    min: 1,
    max: 100,
    description: "Higher % = looser = flag more splits (Zero Trust). Lower % = stricter = only clear-cut even splits. Outbound within this % of 1/N = 'even'.",
    zeroTrust: "100 — flag any split (Zero Trust = never trust).",
    communityTrust: "8 — only clearly even splits.",
    whereUsed: "Behavior: Peeling (even-division detection)",
    section: "peeling",
  },
  {
    key: "historyDepthSparse",
    label: "History Depth (Sparse)",
    min: 10,
    max: 200,
    description: "Tx count below which wallet is 'Sparse History' (CAUTION). Context for peeling: virgin/sparse + peel = higher suspicion.",
    zeroTrust: "100 — require more history.",
    communityTrust: "50 — heuristic-led balance.",
    whereUsed: "Behavior: Peeling (history context)",
    section: "peeling",
  },
  {
    key: "inboundDustCautionRisk",
    label: "Inbound Dust Caution Risk",
    min: 0,
    max: 100,
    description: "Risk score when target receives dust but doesn't send it (passive receipt).",
    zeroTrust: "80 — high caution.",
    communityTrust: "50 — moderate caution.",
    whereUsed: "Behavior: Dusting (inbound-only)",
    section: "dust",
  },
];

/** Preset values for ZeroTrust and CommunityTrust */
export const PRESET_VALUES: Record<string, Record<string, number>> = {
  ZeroTrust: {
    sovereignCap: 0,
    sovereignCapWindowHours: 0,
    maxRiskFloor: 0,
    blockThreshold: 50,
    minConfidenceCeiling: 100,
    dustUsdCeiling: 2,
    matureWalletDustBlockThreshold: 2,
    peelingHeavyRecipients: 5,
    peelingSuspectedRecipients: 2,
    fastPeelWindowMinutes: 15,
    botLikeWindowMinutes: 1,
    evenDivisionTolerance: 100,
    historyDepthSparse: 100,
    inboundDustCautionRisk: 80,
  },
  CommunityTrust: {
    sovereignCap: 500,
    sovereignCapWindowHours: 24,
    maxRiskFloor: 40,
    blockThreshold: 80,
    minConfidenceCeiling: 60,
    dustUsdCeiling: 5,
    matureWalletDustBlockThreshold: 5,
    peelingHeavyRecipients: 10,
    peelingSuspectedRecipients: 2,
    fastPeelWindowMinutes: 30,
    botLikeWindowMinutes: 2,
    evenDivisionTolerance: 8,
    historyDepthSparse: 50,
    inboundDustCautionRisk: 50,
  },
  Custom: {
    ...{ sovereignCap: 500, sovereignCapWindowHours: 24, maxRiskFloor: 40, blockThreshold: 80, minConfidenceCeiling: 60 },
    dustUsdCeiling: 5,
    matureWalletDustBlockThreshold: 5,
    peelingHeavyRecipients: 10,
    peelingSuspectedRecipients: 2,
    fastPeelWindowMinutes: 30,
    botLikeWindowMinutes: 2,
    evenDivisionTolerance: 8,
    historyDepthSparse: 50,
    inboundDustCautionRisk: 50,
  },
  Institutional: {
    sovereignCap: 100_000,
    sovereignCapWindowHours: 24,
    maxRiskFloor: 50,
    blockThreshold: 90,
    minConfidenceCeiling: 60,
    dustUsdCeiling: 5,
    matureWalletDustBlockThreshold: 5,
    peelingHeavyRecipients: 10,
    peelingSuspectedRecipients: 2,
    fastPeelWindowMinutes: 30,
    botLikeWindowMinutes: 2,
    evenDivisionTolerance: 8,
    historyDepthSparse: 50,
    inboundDustCautionRisk: 50,
  },
  /** Time-Sentry: Same base as CommunityTrust but 90% cap reduction 8PM–6AM UTC (Ghost Hours). Higher day cap = more permissive during day; night cap = 10% of this. */
  TimeSentry: {
    sovereignCap: 5000,
    sovereignCapWindowHours: 24,
    maxRiskFloor: 40,
    blockThreshold: 80,
    minConfidenceCeiling: 60,
    dustUsdCeiling: 5,
    matureWalletDustBlockThreshold: 5,
    peelingHeavyRecipients: 10,
    peelingSuspectedRecipients: 2,
    fastPeelWindowMinutes: 30,
    botLikeWindowMinutes: 2,
    evenDivisionTolerance: 8,
    historyDepthSparse: 50,
    inboundDustCautionRisk: 50,
  },
};
